# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - 'master'
      - 'actions-test'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3.5.0
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi 
    - run: flutter build apk
    - run: echo "commit=$(git rev-parse HEAD | head -c 6)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: kosmos-client-${{ env.commit }}-arm64-v8a.apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    - uses: actions/upload-artifact@v3
      with:
        name: kosmos-client-${{ env.commit }}-armeabi-v7a.apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    - uses: actions/upload-artifact@v3
      with:
        name: kosmos-client-${{ env.commit }}-x86_64.apk
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk
    - uses: actions/upload-artifact@v3
      with:
        name: kosmos-client-${{ env.commit }}.apk
        path: build/app/outputs/flutter-apk/app-release.apk
